CREATE TABLE otps (
    email VARCHAR(255) NOT NULL PRIMARY KEY,
    otp VARCHAR(6) NOT NULL,
    expiry TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
